[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "2.0"
regex = "1"
clap = "4.5.23"
walkdir = "2.3"
chrono = "0.4"
zip = "2.0"
filetime = "0.2"
notify = "7.0"
ftp = "3.0.1"
